### ISSUE TITLE
OpenStreet Map

### ISSUE THREAD

**Issue by nigelhorne** [csirtgadgets/google-protocolbuffers-perl#31]
Does it work with OpenStreet Map files?  https://wiki.openstreetmap.org/wiki/PBF_Format

**Comment by vphantom** [comment]
I'm not an authority on this, but since this module ignores all options (except defaults) it seemed risky so I took a deeper look.  Luckily, even though this is a `proto2` parser, it seems to store numeric repeated fields in packed format.  All definitions of repeated numeric fields in OSM are explicitly specified as packed (as they would be by default in `proto3`).

Therefore, I bet it would work.
